name: OWASP Dependency Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*" # Use the latest stable (LTS) version

      - name: Install dependencies
        run: npm install

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: "pricewolves-web-app"
          path: "."
          format: "HTML"
          out: "reports"
          args: "--failOnCVSS 7 --enableRetired"

      - name: Upload Test Results Report
        uses: actions/upload-artifact@master
        with:
          name: dependency-check-report
          path: ${{github.workspace}}/reports
          if-no-files-found: error
          if-exists: replace
